# Generated by Django 4.2.2 on 2023-06-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ManyToManyField(blank=True, to='shop.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_mode',
            field=models.CharField(default='buyer', max_length=6),
        ),
        migrations.RenameModel(
            old_name='Seller',
            new_name='SellerProfile',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='favorite_shops',
            field=models.ManyToManyField(blank=True, related_name='followers', to='account.sellerprofile'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
