# Generated by Django 4.2.2 on 2023-06-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchases',
            field=models.ManyToManyField(blank=True, to='shop.purchase'),
        ),
    ]
